FROM python:3.14-slim-trixie

USER root

ENV LANG=C.UTF-8 \
    LC_ALL=C.UTF-8

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    curl \
    zsh \
    nodejs \
    openssh-client

RUN curl -sS https://starship.rs/install.sh | sh -s -- -y
RUN echo 'eval "$(starship init bash)"' >> /root/.bashrc
RUN echo 'eval "$(starship init zsh)"' >> /root/.zshrc


RUN git config --global credential.helper store && \
    git config --global init.defaultBranch main


WORKDIR /auth_api
ENV PYTHONPATH="/auth_api"

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

RUN mkdir -p /root/.ssh
COPY .ssh/ /root/.ssh/
RUN chmod 700 /root/.ssh
RUN chmod 600 /root/.ssh/*

COPY . .
